In [1]:
import numpy as np

In [2]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)

In [3]:
x = np.array([2.0,3.0,1.0,5.0])

In [4]:
output = softmax(x)
output

array([0.0413707 , 0.11245721, 0.01521943, 0.83095266])

In [5]:
# By Torch

In [6]:
import torch
import torchvision

In [7]:
x = torch.tensor(x)
x

tensor([2., 3., 1., 5.], dtype=torch.float64)

In [8]:
output = torch.softmax(x, dim=0)

In [9]:
output

tensor([0.0414, 0.1125, 0.0152, 0.8310], dtype=torch.float64)